version: '3.9'

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit_app_datamate
    ports:
      - "8501:8501"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - streamlit

  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel
    command: tunnel --no-autoupdate run --url http://nginx:80
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
